apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: sharedspace
      hostPath:
        path: "/var/sharedPodDir"
  containers:
  - name: nginx
    image: nginx:1.7.9
    volumeMounts:
      - mountPath: "/containerMount"
        name: "sharedspace"
    ports:
    - containerPort: 80
