kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: my-pv-claim
   labels:
      app: nginx
spec:
   storageClassName: manual
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 5Gi
